[env]
HK_PKL_BACKEND = "pkl" # TODO remove once upgraded to hk v2

[tools]
"core:rust" = "1.98.1"
"core:java" = "25.0.2"
"aqua:apple/pkl" = "0.32.1"
"aqua:tombi-toml/tombi" = "1.5.3"
"aqua:EmbarkStudios/cargo-deny" = "0.20.2"  # Used for auditing dependencies (hk cargo deny step)
"aqua:jdx/hk" = "1.58.1"                       # Used for linting, formatting & git hooks
"aqua:rvben/rumdl" = "0.2.73"                 # Used for linting & formatting markdown
"github:zizmorcore/zizmor" = "v1.30.1"        # Used for statically analyzing github actions
