# * Backend Priority Order: Core, Aqua, Github, Package Manager (cargo, npm, pipx)

[tools]
#* Main
"core:rust" = "1.98.1"
#* Linting
"aqua:jdx/hk" = "2.1.0"                    # Used for running linting, formatting & git hooks
"aqua:mikefarah/yq" = "4.53.6"             # Used for validating & formatting JSON & toml parsing
"aqua:tombi-toml/tombi" = "1.5.5"          # Used for linting & formatting toml
"aqua:EmbarkStudios/cargo-deny" = "0.20.2" # Used for auditing dependencies (hk cargo deny step)
"aqua:rvben/rumdl" = "0.2.75"              # Used for linting & formatting markdown
"aqua:loeffel-io/ls-lint" = "2.3.1"        # Used for enforcing folder & file naming conventions
"aqua:lycheeverse/lychee" = "0.24.2"       # Used for checking for dead links
"github:kucherenko/jscpd" = "v5.3.0"       # Used for detecting code duplication
"github:zizmorcore/zizmor" = "v1.30.1"     # Used for statically analyzing github actions
"github:mongodb/kingfisher" = "v2.5.0"     # Used for checking for leaked credentials & secrets

[settings]
lockfile = true
