# * Backend Priority Order: Core, Aqua, Github, Package Manager (cargo, npm, pipx)

[env]
HK_PKL_BACKEND = "pkl" # TODO remove once upgraded to hk v2

[tools]
"core:rust" = "1.98.1"
"core:java" = "25.0.2"
"aqua:apple/pkl" = "0.32.1"
"aqua:mikefarah/yq" = "4.53.6"             # Used for validating & formatting JSON & toml parsing
"aqua:tombi-toml/tombi" = "1.5.5"
"aqua:EmbarkStudios/cargo-deny" = "0.20.2" # Used for auditing dependencies (hk cargo deny step)
"aqua:jdx/hk" = "2.0.1"                   # Used for linting, formatting & git hooks
"aqua:rvben/rumdl" = "0.2.73"              # Used for linting & formatting markdown
"aqua:loeffel-io/ls-lint" = "2.3.1"        # Used for enforcing folder & file naming conventions
"aqua:lycheeverse/lychee" = "0.24.2"       # Used for checking for dead links
"github:kucherenko/jscpd" = "v5.2.1"       # Used for detecting code duplication
"github:zizmorcore/zizmor" = "v1.30.1"     # Used for statically analyzing github actions
"github:mongodb/kingfisher" = "v2.4.0"     # Used for checking for leaked credentials & secrets

[settings]
lockfile = true
