//! Two-way sync for `back_propagate` templates (Milestone 5).
//!
//! Hand-edits to watched generated files diff back into project overrides so
//! the next template bump reproduces them. Every fold passes through an
//! in-memory safety replay (template pipeline re-run, compared against the
//! expected bytes); mismatches fail loudly with the conflicting content saved
//! to a temp snapshot, leaving files untouched, and watch mode keeps running.
//! Template updates win over pending edits, then the captured diff reapplies
//! (three-way merge for structured formats).

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use serde_json::Value;

use crate::config::ArrayPolicy;
use crate::merge::{self, DELETE_MARKER, DocFormat, EffectiveStrategy};

/// Conflict snapshot directory name inside the system temp dir.
///
/// On safety-check mismatch the conflicting generated content is recoverable
/// here at `<stem>.<timestamp>.conflict.<ext>`.
pub const CONFLICT_SNAPSHOT_DIR_NAME: &str = "templatry-conflicts";

/// One group member's fresh file contents for back-propagation.
pub struct MemberView<'a> {
    /// Contributing template name.
    pub name: &'a str,
    /// Contributing template labels.
    pub labels: &'a BTreeSet<String>,
    /// Current template file text.
    pub template_text: &'a str,
    /// Current override file text (`None` when missing).
    pub override_text: Option<&'a str>,
    /// Resolved strategy.
    pub strategy: EffectiveStrategy,
    /// Merge policy for structured strategies.
    pub policy: ArrayPolicy,
    /// Whether this member accepts back-propagation.
    pub back_propagate: bool,
}

/// Back-propagation outcome: applied, or nothing to do.
///
/// All failure modes are loud [`crate::Error`]s (mismatch with snapshot,
/// ambiguity, unparsable files); watch mode logs them and keeps watching.
#[derive(Debug)]
pub enum BackpropOutcome {
    /// Exactly one contributor accepted the edit.
    Applied {
        /// Contributing template name (owns the rewritten override).
        member: String,
        /// New override file content.
        new_override_text: String,
        /// Forward-regenerated bytes (equal to the safety target).
        replay_bytes: Vec<u8>,
    },
    /// No back-propagate member, or no detectable change.
    NoChange,
}

/// Fold a hand-edit into overrides: `last_bytes` is the previous generated
/// state, `current_bytes` the hand-edited state (the safety target).
pub fn backpropagate(
    dest: &Path,
    last_bytes: &[u8],
    current_bytes: &[u8],
    members: &[MemberView<'_>],
) -> crate::Result<BackpropOutcome> {
    let candidates: Vec<&MemberView<'_>> = members
        .iter()
        .filter(|member| member.back_propagate)
        .collect();
    if candidates.is_empty() || last_bytes == current_bytes {
        return Ok(BackpropOutcome::NoChange);
    }
    match candidates[0].strategy {
        EffectiveStrategy::Structured(format) => {
            let base = parse_generated(last_bytes, dest, format, "previous")?;
            let target = parse_generated(current_bytes, dest, format, "current")?;
            let ops = diff_values(&base, &target);
            if ops.is_empty() {
                return Ok(BackpropOutcome::NoChange);
            }
            try_candidates(
                dest,
                members,
                &candidates,
                &ops,
                &target,
                current_bytes,
                true,
            )
        }
        text => {
            require_single_text_member(dest, members)?;
            let current = decode(
                current_bytes,
                dest,
                "generated file (hand-edited content must be UTF-8)",
            )?;
            let tentative = fold_text(
                candidates[0].template_text,
                &current,
                text,
                candidates[0].name,
                dest,
            )?;
            replay_text(dest, candidates[0], &tentative, current_bytes, true)
        }
    }
}

/// Reapply a captured hand-edit after a template update won.
///
/// Three-way merge for structured formats: the user diff (last vs captured)
/// applies onto the fresh forward output, folds into overrides against the
/// new template, and replays must reproduce that desired output. Text formats
/// fold the captured bytes against the new template and must reproduce them
/// exactly (template-region edits fail loudly).
pub fn reapply(
    dest: &Path,
    last_bytes: &[u8],
    captured_bytes: &[u8],
    forward_bytes: &[u8],
    members: &[MemberView<'_>],
) -> crate::Result<BackpropOutcome> {
    let candidates: Vec<&MemberView<'_>> = members
        .iter()
        .filter(|member| member.back_propagate)
        .collect();
    if candidates.is_empty() || last_bytes == captured_bytes {
        return Ok(BackpropOutcome::NoChange);
    }
    match candidates[0].strategy {
        EffectiveStrategy::Structured(format) => {
            let base = parse_generated(last_bytes, dest, format, "previous")?;
            let captured = parse_generated(captured_bytes, dest, format, "hand-edited")?;
            let forward = parse_generated(forward_bytes, dest, format, "regenerated")?;
            let ops = diff_values(&base, &captured);
            if ops.is_empty() {
                return Ok(BackpropOutcome::NoChange);
            }
            let mut desired = forward;
            apply_ops_plain(&mut desired, &ops);
            let desired_bytes = merge::serialize_doc(&desired, format)?.into_bytes();
            try_candidates(
                dest,
                members,
                &candidates,
                &ops,
                &desired,
                &desired_bytes,
                false,
            )
        }
        text => {
            require_single_text_member(dest, members)?;
            let captured = decode(captured_bytes, dest, "hand-edited content must be UTF-8")?;
            let tentative = fold_text(
                candidates[0].template_text,
                &captured,
                text,
                candidates[0].name,
                dest,
            )?;
            replay_text(dest, candidates[0], &tentative, captured_bytes, false)
        }
    }
}

/// Text back-propagation needs exactly one group member to attribute edits.
fn require_single_text_member(dest: &Path, members: &[MemberView<'_>]) -> crate::Result<()> {
    if members.len() == 1 {
        return Ok(());
    }
    Err(crate::invalid(
        dest,
        "back propagation into a shared text destination cannot attribute edits to one override: use structured merge strategies for label-split files".to_string(),
    ))
}

/// Parse generated bytes as a structured document for diffing.
fn parse_generated(
    bytes: &[u8],
    dest: &Path,
    format: DocFormat,
    which: &str,
) -> crate::Result<Value> {
    let text = decode(
        bytes,
        dest,
        &format!("{which} generated content must be UTF-8"),
    )?;
    merge::parse_doc(
        &text,
        format,
        &format!("{which} generated file `{}`", dest.display()),
    )
}

/// Decode bytes with an actionable diagnostic.
fn decode(bytes: &[u8], dest: &Path, what: &str) -> crate::Result<String> {
    String::from_utf8(bytes.to_vec())
        .map_err(|err| crate::invalid(dest, format!("{what} is not valid UTF-8: {err}")))
}

// ---- Diff -------------------------------------------------------------------

/// One user edit operation: set a path, or delete it.
#[derive(Debug, Clone, PartialEq)]
enum DiffOp {
    /// Path set to a value (added keys, changed scalars, wholesale arrays).
    Set { path: Vec<String>, value: Value },
    /// Path removed.
    Delete { path: Vec<String> },
}

/// Diff previous vs current generated documents into operations.
///
/// Objects recurse; arrays compare wholesale (no index paths); scalars and
/// type changes record as sets.
fn diff_values(last: &Value, current: &Value) -> Vec<DiffOp> {
    let mut ops = Vec::new();
    diff_into(last, current, &mut Vec::new(), &mut ops);
    ops
}

fn diff_into(last: &Value, current: &Value, path: &mut Vec<String>, ops: &mut Vec<DiffOp>) {
    match (last, current) {
        (Value::Object(last_map), Value::Object(current_map)) => {
            for (key, current_value) in current_map {
                path.push(key.clone());
                match last_map.get(key) {
                    Some(last_value) => diff_into(last_value, current_value, path, ops),
                    None => ops.push(DiffOp::Set {
                        path: path.clone(),
                        value: current_value.clone(),
                    }),
                }
                path.pop();
            }
            for key in last_map.keys() {
                if !current_map.contains_key(key) {
                    path.push(key.clone());
                    ops.push(DiffOp::Delete { path: path.clone() });
                    path.pop();
                }
            }
        }
        (Value::Array(last_items), Value::Array(current_items)) => {
            if last_items != current_items {
                ops.push(DiffOp::Set {
                    path: path.clone(),
                    value: current.clone(),
                });
            }
        }
        (last_value, current_value) => {
            if last_value != current_value {
                ops.push(DiffOp::Set {
                    path: path.clone(),
                    value: current_value.clone(),
                });
            }
        }
    }
}

// ---- Path helpers -----------------------------------------------------------

/// Read a nested value by path segments (empty path reads the document).
fn get_path<'a>(value: &'a Value, path: &[String]) -> Option<&'a Value> {
    let mut current = value;
    for segment in path {
        current = current.get(segment)?;
    }
    Some(current)
}

/// Set a nested value, creating intermediate objects (errors through arrays,
/// scalars, or at the document root whole-replace... see below).
///
/// An empty path replaces the whole document (only used when the diff itself
/// replaced the root, e.g. object-to-array).
fn set_path_strict(slot: &mut Value, path: &[String], value: Value) -> crate::Result<()> {
    let Some((first, rest)) = path.split_first() else {
        *slot = value;
        return Ok(());
    };
    if slot.is_null() {
        *slot = Value::Object(Default::default());
    }
    match slot {
        Value::Object(map) => {
            let child = map
                .entry(first.clone())
                .or_insert(Value::Object(Default::default()));
            if !rest.is_empty() && !child.is_object() && !child.is_null() {
                return Err(crate::invalid(
                    Path::new("templatry.source.toml"),
                    format!(
                        "cannot fold change at `{}`: `{first}` is not an object in the override",
                        path.join(".")
                    ),
                ));
            }
            set_path_strict(child, rest, value)
        }
        _ => Err(crate::invalid(
            Path::new("templatry.source.toml"),
            format!(
                "cannot fold change at `{}`: override holds a non-object where an object is needed",
                path.join(".")
            ),
        )),
    }
}

/// Forgiving set for desired-output computation: replaces anything in the way.
fn set_path_forgiving(slot: &mut Value, path: &[String], value: Value) {
    let Some((first, rest)) = path.split_first() else {
        *slot = value;
        return;
    };
    if !slot.is_object() {
        *slot = Value::Object(Default::default());
    }
    if let Value::Object(map) = slot {
        let child = map
            .entry(first.clone())
            .or_insert(Value::Object(Default::default()));
        set_path_forgiving(child, rest, value);
    }
}

/// Delete a nested value (no-op when absent; empty path is an error).
///
/// Deliberately leaves emptied parent objects in place: pruning them could
/// drop user-written structure the safety replay expects.
fn remove_path(slot: &mut Value, path: &[String]) -> crate::Result<()> {
    let Some((first, rest)) = path.split_first() else {
        return Err(crate::invalid(
            Path::new("templatry.source.toml"),
            "cannot fold a document-root deletion: delete the override file instead".to_string(),
        ));
    };
    match slot {
        Value::Object(map) => {
            if rest.is_empty() {
                map.remove(first);
            } else if let Some(child) = map.get_mut(first) {
                remove_path(child, rest)?;
            }
            Ok(())
        }
        _ => Ok(()),
    }
}

/// Apply operations plainly (desired-output computation, no template logic).
fn apply_ops_plain(base: &mut Value, ops: &[DiffOp]) {
    for op in ops {
        match op {
            DiffOp::Set { path, value } => set_path_forgiving(base, path, value.clone()),
            DiffOp::Delete { path } => {
                let _ = remove_path(base, path);
            }
        }
    }
}

// ---- Structured fold ----------------------------------------------------------

/// Fold operations into one candidate's override.
///
/// Changed values matching the (new) template are cleaned out of the override
/// instead of pinned, so future template bumps flow through; deleted keys the
/// template still defines become `{DELETE_MARKER}`, others are removed.
fn fold_candidate(
    candidate: &MemberView<'_>,
    format: DocFormat,
    ops: &[DiffOp],
) -> crate::Result<Value> {
    let mut tentative = match candidate.override_text {
        Some(text) => merge::parse_doc(
            text,
            format,
            &format!("override for template `{}`", candidate.name),
        )?,
        None => Value::Null,
    };
    let template_value = merge::parse_doc(
        candidate.template_text,
        format,
        &format!("template `{}`", candidate.name),
    )?;
    for op in ops {
        match op {
            DiffOp::Set { path, value } => {
                if !path.is_empty() && get_path(&template_value, path) == Some(value) {
                    remove_path(&mut tentative, path)?;
                } else {
                    set_path_strict(&mut tentative, path, value.clone())?;
                }
            }
            DiffOp::Delete { path } => {
                if get_path(&template_value, path).is_some() {
                    set_path_strict(
                        &mut tentative,
                        path,
                        Value::String(DELETE_MARKER.to_string()),
                    )?;
                } else {
                    remove_path(&mut tentative, path)?;
                }
            }
        }
    }
    Ok(tentative)
}

/// Try every candidate: fold, replay the full pipeline, compare.
///
/// Pipeline errors (e.g. combine conflicts from a wrong attribution) reject
/// the candidate. Zero passes fail loudly with a snapshot; several passes
/// mean genuine ambiguity.
fn try_candidates(
    dest: &Path,
    members: &[MemberView<'_>],
    candidates: &[&MemberView<'_>],
    ops: &[DiffOp],
    target: &Value,
    target_bytes: &[u8],
    generated_untouched: bool,
) -> crate::Result<BackpropOutcome> {
    let mut passing = Vec::new();
    for candidate in candidates {
        let format = match candidate.strategy {
            EffectiveStrategy::Structured(format) => format,
            _ => continue,
        };
        let tentative = match fold_candidate(candidate, format, ops) {
            Ok(tentative) => tentative,
            Err(err) => {
                tracing::debug!(
                    template = candidate.name,
                    "back-propagation fold rejected: {err}"
                );
                continue;
            }
        };
        match safety_replay(candidate, members, &tentative, target) {
            Ok(replay_bytes) => passing.push((candidate.name, tentative, replay_bytes, format)),
            Err(reason) => {
                tracing::debug!(
                    template = candidate.name,
                    "back-propagation replay rejected: {reason}"
                );
            }
        }
    }
    match passing.len() {
        0 => {
            let snapshot = write_snapshot(dest, target_bytes);
            Err(mismatch_error(dest, &snapshot, generated_untouched))
        }
        1 => {
            let (name, tentative, replay_bytes, format) =
                passing.pop().expect("one passing candidate");
            Ok(BackpropOutcome::Applied {
                member: name.to_string(),
                new_override_text: merge::serialize_doc(&tentative, format)?,
                replay_bytes,
            })
        }
        _ => {
            let mut names: Vec<&str> = passing.iter().map(|(name, _, _, _)| *name).collect();
            names.sort();
            Err(crate::invalid(
                dest,
                format!(
                    "back propagation is ambiguous: the edit is reproducible through {}: edit the override files directly to disambiguate",
                    names
                        .iter()
                        .map(|name| format!("`{name}`"))
                        .collect::<Vec<_>>()
                        .join(", ")
                ),
            ))
        }
    }
}

/// Replay the full pipeline with a tentative override and compare.
///
/// Returns the replay bytes on semantic equality, else a rejection reason.
fn safety_replay(
    candidate: &MemberView<'_>,
    members: &[MemberView<'_>],
    tentative: &Value,
    target: &Value,
) -> Result<Vec<u8>, String> {
    let format = match candidate.strategy {
        EffectiveStrategy::Structured(format) => format,
        _ => return Err("non-structured candidate in structured replay".to_string()),
    };
    let tentative_text = merge::serialize_doc(tentative, format).map_err(|err| format!("{err}"))?;
    let mut contributions = Vec::with_capacity(members.len());
    for member in members {
        let text = if member.name == candidate.name {
            Some(tentative_text.as_str())
        } else {
            member.override_text
        };
        let rendered = crate::generate::render_contents(
            member.template_text,
            text,
            member.strategy,
            member.policy,
            member.name,
        )
        .map_err(|err| format!("{err}"))?;
        match rendered {
            merge::Rendered::Structured { value, .. } => contributions.push(merge::Contribution {
                template: member.name,
                labels: member.labels,
                value,
            }),
            merge::Rendered::Text(_) => {
                return Err("mixed text output in structured replay".to_string());
            }
        }
    }
    let combined = merge::combine_structured(&contributions).map_err(|err| format!("{err}"))?;
    let replay_text = merge::serialize_doc(&combined, format).map_err(|err| format!("{err}"))?;
    let replay: Value =
        merge::parse_doc(&replay_text, format, "safety replay").map_err(|err| format!("{err}"))?;
    if &replay == target {
        Ok(replay_text.into_bytes())
    } else {
        Err("replay output differs from the generated file".to_string())
    }
}

// ---- Text fold ------------------------------------------------------------------

/// Fold a hand-edit into a text override.
///
/// `replace` takes the content verbatim; `append_*` strips the known template
/// portion (template-region edits fail loudly instead of misattributing).
fn fold_text(
    template_text: &str,
    current: &str,
    strategy: EffectiveStrategy,
    name: &str,
    dest: &Path,
) -> crate::Result<String> {
    match strategy {
        EffectiveStrategy::Replace => Ok(current.to_string()),
        EffectiveStrategy::AppendBottom => current
            .strip_prefix(template_text)
            .and_then(|rest| rest.strip_prefix('\n').or(Some(rest)))
            .map(str::to_string)
            .ok_or_else(|| {
                crate::invalid(
                    dest,
                    format!(
                        "template `{name}`: the edit touches the template portion of an `append_bottom` file, which cannot fold back: edit the override file directly"
                    ),
                )
            }),
        EffectiveStrategy::AppendTop => current
            .strip_suffix(template_text)
            .and_then(|rest| rest.strip_suffix('\n').or(Some(rest)))
            .map(str::to_string)
            .ok_or_else(|| {
                crate::invalid(
                    dest,
                    format!(
                        "template `{name}`: the edit touches the template portion of an `append_top` file, which cannot fold back: edit the override file directly"
                    ),
                )
            }),
        EffectiveStrategy::Structured(_) => Err(crate::invalid(
            dest,
            "internal error: text fold called for a structured template".to_string(),
        )),
        EffectiveStrategy::None => Err(crate::invalid(
            dest,
            format!(
                "template `{name}`: strategy `none` copies the template verbatim with no override to fold into"
            ),
        )),
    }
}

/// Replay a text candidate and compare bytes exactly.
fn replay_text(
    dest: &Path,
    candidate: &MemberView<'_>,
    tentative: &str,
    target_bytes: &[u8],
    generated_untouched: bool,
) -> crate::Result<BackpropOutcome> {
    let rendered = crate::generate::render_contents(
        candidate.template_text,
        Some(tentative),
        candidate.strategy,
        candidate.policy,
        candidate.name,
    )
    .map_err(|err| {
        tracing::debug!(
            template = candidate.name,
            "back-propagation replay rejected: {err}"
        );
        let snapshot = write_snapshot(dest, target_bytes);
        mismatch_error(dest, &snapshot, generated_untouched)
    })?;
    match rendered {
        merge::Rendered::Text(bytes) if bytes.as_bytes() == target_bytes => {
            Ok(BackpropOutcome::Applied {
                member: candidate.name.to_string(),
                new_override_text: tentative.to_string(),
                replay_bytes: bytes.into_bytes(),
            })
        }
        _ => {
            let snapshot = write_snapshot(dest, target_bytes);
            Err(mismatch_error(dest, &snapshot, generated_untouched))
        }
    }
}

// ---- Snapshots and diagnostics ----------------------------------------------------

/// Save conflicting content for recovery; best-effort, always returns the path.
pub(crate) fn write_snapshot(dest: &Path, content: &[u8]) -> PathBuf {
    let dir = std::env::temp_dir().join(CONFLICT_SNAPSHOT_DIR_NAME);
    let stem = dest
        .file_stem()
        .and_then(|stem| stem.to_str())
        .unwrap_or("generated");
    let extension = dest
        .extension()
        .and_then(|extension| extension.to_str())
        .map(|extension| format!(".{extension}"))
        .unwrap_or_default();
    let timestamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    let path = dir.join(format!("{stem}.{timestamp}.conflict{extension}"));
    if let Err(err) = std::fs::create_dir_all(&dir).and_then(|_| std::fs::write(&path, content)) {
        tracing::warn!("cannot write conflict snapshot: {err}");
    }
    path
}

/// Loud safety-mismatch error naming the recovery snapshot.
fn mismatch_error(dest: &Path, snapshot: &Path, generated_untouched: bool) -> crate::Error {
    let state = if generated_untouched {
        "both files left untouched"
    } else {
        "template output kept"
    };
    crate::invalid(
        dest,
        format!(
            "back propagation safety check failed: replaying the computed override through the template does not reproduce the generated file ({state}). Common cause: array edits under `array_policy = \"union\"`, which re-adds template items — switch the template to `\"replace\"` or edit the override directly. Conflicting generated content saved to `{}`",
            snapshot.display()
        ),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn labels(names: &[&str]) -> BTreeSet<String> {
        names.iter().map(|name| name.to_string()).collect()
    }

    fn view<'a>(
        name: &'a str,
        label_set: &'a BTreeSet<String>,
        template_text: &'a str,
        override_text: Option<&'a str>,
        strategy: EffectiveStrategy,
    ) -> MemberView<'a> {
        MemberView {
            name,
            labels: label_set,
            template_text,
            override_text,
            strategy,
            policy: ArrayPolicy::Union,
            back_propagate: true,
        }
    }

    fn json_member<'a>(
        name: &'a str,
        label_set: &'a BTreeSet<String>,
        template_text: &'a str,
        override_text: Option<&'a str>,
    ) -> MemberView<'a> {
        view(
            name,
            label_set,
            template_text,
            override_text,
            EffectiveStrategy::Structured(DocFormat::Json),
        )
    }

    fn parse(text: &str) -> Value {
        merge::parse_doc(text, DocFormat::Json, "test").expect("test json parses")
    }

    fn last_of(template_text: &str, override_text: Option<&str>) -> Vec<u8> {
        let base = parse(template_text);
        let merged = match override_text {
            Some(text) => {
                merge::merge_structured(base, parse(text), ArrayPolicy::Union, "t").unwrap()
            }
            None => base,
        };
        merge::serialize_doc(&merged, DocFormat::Json)
            .unwrap()
            .into_bytes()
    }

    fn applied(outcome: BackpropOutcome) -> (String, String, Vec<u8>) {
        match outcome {
            BackpropOutcome::Applied {
                member,
                new_override_text,
                replay_bytes,
            } => {
                assert!(!new_override_text.is_empty());
                (member, new_override_text, replay_bytes)
            }
            BackpropOutcome::NoChange => panic!("expected Applied, got NoChange"),
        }
    }

    #[test]
    fn scalar_change_folds_into_override() {
        let labels = labels(&["rust"]);
        let last = last_of("{\"a\": 1, \"b\": 2}", Some("{\"b\": 20}"));
        let current = b"{\"a\": 1, \"b\": 30}\n";
        let members = [json_member(
            "app",
            &labels,
            "{\"a\": 1, \"b\": 2}",
            Some("{\"b\": 20}"),
        )];
        let outcome = backpropagate(Path::new("out.json"), &last, current, &members).unwrap();
        let (member, _, replay) = applied(outcome);
        assert_eq!(member, "app");
        assert_eq!(
            parse(std::str::from_utf8(&replay).unwrap()),
            parse("{\"a\": 1, \"b\": 30}")
        );
    }

    #[test]
    fn added_key_folds_into_override() {
        let labels = labels(&["rust"]);
        let last = last_of("{\"a\": 1}", None);
        let current = b"{\"a\": 1, \"fresh\": true}\n";
        let members = [json_member("app", &labels, "{\"a\": 1}", None)];
        let outcome = backpropagate(Path::new("out.json"), &last, current, &members).unwrap();
        let (_, _, replay) = applied(outcome);
        assert_eq!(
            parse(std::str::from_utf8(&replay).unwrap()),
            parse("{\"a\": 1, \"fresh\": true}")
        );
    }

    #[test]
    fn deleted_template_key_becomes_marker() {
        let labels = labels(&["rust"]);
        let last = last_of("{\"drop\": 1, \"keep\": 2}", None);
        let current = b"{\"keep\": 2}\n";
        let members = [json_member(
            "app",
            &labels,
            "{\"drop\": 1, \"keep\": 2}",
            None,
        )];
        let outcome = backpropagate(Path::new("out.json"), &last, current, &members).unwrap();
        match outcome {
            BackpropOutcome::Applied {
                member: _,
                new_override_text,
                ..
            } => {
                assert_eq!(
                    parse(&new_override_text),
                    parse("{\"drop\": \"_TEMPLATRY_DELETE_\"}")
                );
            }
            BackpropOutcome::NoChange => panic!("expected Applied"),
        }
    }

    #[test]
    fn deleted_override_key_leaves_the_override() {
        let labels = labels(&["rust"]);
        let last = last_of("{\"a\": 1}", Some("{\"extra\": 9}"));
        let current = b"{\"a\": 1}\n";
        let members = [json_member(
            "app",
            &labels,
            "{\"a\": 1}",
            Some("{\"extra\": 9}"),
        )];
        let outcome = backpropagate(Path::new("out.json"), &last, current, &members).unwrap();
        match outcome {
            BackpropOutcome::Applied {
                member: _,
                new_override_text,
                ..
            } => {
                assert_eq!(parse(&new_override_text), parse("{}"));
            }
            BackpropOutcome::NoChange => panic!("expected Applied"),
        }
    }

    #[test]
    fn revert_to_template_value_cleans_the_override() {
        let labels = labels(&["rust"]);
        let last = last_of("{\"k\": 1}", Some("{\"k\": 2}"));
        let current = b"{\"k\": 1}\n";
        let members = [json_member(
            "app",
            &labels,
            "{\"k\": 1}",
            Some("{\"k\": 2}"),
        )];
        let outcome = backpropagate(Path::new("out.json"), &last, current, &members).unwrap();
        match outcome {
            BackpropOutcome::Applied {
                member: _,
                new_override_text,
                replay_bytes,
            } => {
                assert_eq!(parse(&new_override_text), parse("{}"));
                assert_eq!(
                    parse(std::str::from_utf8(&replay_bytes).unwrap()),
                    parse("{\"k\": 1}")
                );
            }
            BackpropOutcome::NoChange => panic!("expected Applied"),
        }
    }

    #[test]
    fn array_edit_under_union_fails_loudly() {
        let labels = labels(&["rust"]);
        let last = last_of("{\"l\": [1, 2]}", None);
        let current = b"{\"l\": [2]}\n";
        let members = [json_member("app", &labels, "{\"l\": [1, 2]}", None)];
        let err = backpropagate(Path::new("out.json"), &last, current, &members).unwrap_err();
        let message = err.to_string();
        assert!(message.contains("safety check failed"), "{message}");
        assert!(message.contains("union"), "{message}");
        assert!(message.contains("saved to"), "{message}");
    }

    #[test]
    fn identical_edits_are_ambiguous() {
        let rust = labels(&["rust"]);
        let dart = labels(&["dart"]);
        let last = last_of("{\"a\": 1}", None);
        let current = b"{\"a\": 1, \"z\": 3}\n";
        let members = [
            json_member("rust-part", &rust, "{\"a\": 1}", None),
            json_member("dart-part", &dart, "{\"a\": 1}", None),
        ];
        let err = backpropagate(Path::new("out.json"), &last, current, &members).unwrap_err();
        let message = err.to_string();
        assert!(message.contains("ambiguous"), "{message}");
        assert!(message.contains("rust-part"), "{message}");
        assert!(message.contains("dart-part"), "{message}");
    }

    #[test]
    fn shared_edit_scopes_to_the_right_contributor() {
        let rust = labels(&["rust"]);
        let dart = labels(&["dart"]);
        let rust_last = parse("{\"x\": 1}");
        let dart_last = parse("{\"y\": 1}");
        let combined = {
            let contributions = [
                merge::Contribution {
                    template: "a",
                    labels: &rust,
                    value: rust_last,
                },
                merge::Contribution {
                    template: "b",
                    labels: &dart,
                    value: dart_last,
                },
            ];
            merge::serialize_doc(
                &merge::combine_structured(&contributions).unwrap(),
                DocFormat::Json,
            )
            .unwrap()
            .into_bytes()
        };
        let current = b"{\"x\": 2, \"y\": 1}\n";
        let members = [
            json_member("a", &rust, "{\"x\": 1}", None),
            json_member("b", &dart, "{\"y\": 1}", None),
        ];
        let outcome = backpropagate(Path::new("out.json"), &combined, current, &members).unwrap();
        let (member, _, replay) = applied(outcome);
        assert_eq!(member, "a");
        assert_eq!(
            parse(std::str::from_utf8(&replay).unwrap()),
            parse("{\"x\": 2, \"y\": 1}")
        );
    }

    #[test]
    fn no_change_and_no_candidates() {
        let labels = labels(&["rust"]);
        let last = last_of("{\"a\": 1}", None);
        let members = [json_member("app", &labels, "{\"a\": 1}", None)];
        assert!(matches!(
            backpropagate(Path::new("o"), &last, &last, &members).unwrap(),
            BackpropOutcome::NoChange
        ));

        let mut plain = view(
            "app",
            &labels,
            "{\"a\": 1}",
            None,
            EffectiveStrategy::Structured(DocFormat::Json),
        );
        plain.back_propagate = false;
        assert!(matches!(
            backpropagate(Path::new("o"), &last, b"{\"a\": 2}", &[plain]).unwrap(),
            BackpropOutcome::NoChange
        ));
    }

    #[test]
    fn text_append_round_trip() {
        let labels = labels(&[]);
        let template_text = "TEMPLATRY\n";
        let members = [view(
            "banner",
            &labels,
            template_text,
            None,
            EffectiveStrategy::AppendBottom,
        )];
        let last = b"TEMPLATRY\n";
        let current = b"TEMPLATRY\n\nO=1\n";
        let outcome = backpropagate(Path::new("out.txt"), last, current, &members).unwrap();
        let (member, _, replay) = applied(outcome);
        assert_eq!(member, "banner");
        assert_eq!(replay, current);
    }

    #[test]
    fn text_template_region_edit_fails() {
        let labels = labels(&[]);
        let members = [view(
            "banner",
            &labels,
            "TEMPLATRY\n",
            None,
            EffectiveStrategy::AppendBottom,
        )];
        let err = backpropagate(Path::new("out.txt"), b"TEMPLATRY\n", b"CHANGED\n", &members)
            .unwrap_err();
        assert!(err.to_string().contains("template portion"), "{err:?}");
    }

    #[test]
    fn none_strategy_has_no_override_to_fold_into() {
        let labels = labels(&[]);
        let members = [view(
            "license",
            &labels,
            "MIT\n",
            Some("WRONG\n"),
            EffectiveStrategy::None,
        )];
        let err =
            backpropagate(Path::new("out.txt"), b"MIT\n", b"CHANGED\n", &members).unwrap_err();
        assert!(
            err.to_string().contains("no override to fold into"),
            "{err:?}"
        );
    }

    #[test]
    fn replace_round_trip() {
        let labels = labels(&[]);
        let members = [view(
            "env",
            &labels,
            "A=template\n",
            Some("A=1\n"),
            EffectiveStrategy::Replace,
        )];
        let outcome = backpropagate(Path::new("out.env"), b"A=1\n", b"A=2\n", &members).unwrap();
        let (_, _, replay) = applied(outcome);
        assert_eq!(replay, b"A=2\n");
    }

    #[test]
    fn reapply_survives_a_template_bump() {
        let labels = labels(&["rust"]);
        let template_old = "{\"k\": 1, \"u\": \"old\"}";
        let last = last_of(template_old, None);
        let captured = b"{\"k\": 2, \"u\": \"old\"}\n";

        let template_new = "{\"k\": 1, \"u\": \"new\", \"n\": true}";
        let forward = merge::serialize_doc(&parse(template_new), DocFormat::Json)
            .unwrap()
            .into_bytes();
        let members = [json_member("app", &labels, template_new, None)];
        let outcome = reapply(Path::new("out.json"), &last, captured, &forward, &members).unwrap();
        let (member, _, replay) = applied(outcome);
        assert_eq!(member, "app");
        assert_eq!(
            parse(std::str::from_utf8(&replay).unwrap()),
            parse("{\"k\": 2, \"u\": \"new\", \"n\": true}")
        );
    }

    #[test]
    fn snapshot_file_is_written() {
        let dir = tempfile::tempdir().expect("tempdir");
        let dest = dir.path().join("settings.json");
        let path = write_snapshot(&dest, b"{}");
        assert!(path.exists());
        assert_eq!(std::fs::read(&path).unwrap(), b"{}");
        let name = path.file_name().expect("name").to_string_lossy();
        assert!(name.starts_with("settings.") && name.contains(".conflict.json"));
    }
}
