//! File watching, regeneration dispatch, and back-propagation triggers.
//!
//! Milestones 4–5. `watchexec` subscription, per-path regeneration,
//! config-change restart, debounce, and the self-trigger write guard,
//! following the `smartworkspace` pattern. Override changes regenerate only
//! their destination group; project/source config changes trigger a full
//! reload plus resubscribe. Generated files of `back_propagate` templates
//! fold hand-edits back into overrides through [`crate::backprop`] safety
//! replays; failures log loudly with recovery snapshots and keep watching.
//! Template updates win over pending hand-edits, then the captured diff
//! reapplies onto the fresh output.

use std::collections::{BTreeMap, HashMap, HashSet};
use std::path::{Path, PathBuf};
use std::sync::{
    Arc, Mutex,
    atomic::{AtomicBool, Ordering},
};
use std::time::{Duration, Instant};

use watchexec::Watchexec;
use watchexec_signals::Signal;

use crate::backprop::{self, BackpropOutcome, MemberView};
use crate::config::{SOURCE_CONFIG_FILENAME, SourceKind};
use crate::generate::{self, GroupMember, Options, ProjectContext};

/// Self-trigger guard window: our own writes arriving inside it are ignored.
///
/// Matches the `smartworkspace` 500 ms debounce.
const GUARD_WINDOW: Duration = Duration::from_millis(500);

/// Reload retry delay when a cycle fails to start (broken config mid-watch).
const RELOAD_RETRY: Duration = Duration::from_secs(2);

/// Watch for changes and regenerate; runs until interrupted.
///
/// Each cycle loads the project, captures pending hand-edits, writes the full
/// plan once (template wins), reapplies captured edits, then watches until a
/// config change forces a reload or an interrupt quits. Only the initial load
/// fails fast; reload failures log and retry so a broken save never kills the
/// watcher.
pub async fn run(options: &Options) -> crate::Result<()> {
    let shared = Shared::new();
    let mut cycle = Cycle::start(options, &shared).await?;
    while let SpinOutcome::Reload = cycle.spin().await? {
        tracing::info!("configuration changed, reloading");
        cycle = loop {
            match Cycle::start(options, &shared).await {
                Ok(cycle) => break cycle,
                Err(err) => {
                    tracing::error!("reload failed: {err:?} (retrying)");
                    tokio::time::sleep(RELOAD_RETRY).await;
                }
            }
        };
    }
    tracing::info!("watch stopped");
    Ok(())
}

/// State shared across reload cycles: baselines, write guard, regen lock.
#[derive(Clone)]
struct Shared {
    tracker: Arc<Mutex<LastKnown>>,
    guard: Arc<WriteGuard>,
    regen_lock: Arc<tokio::sync::Mutex<()>>,
}

impl Shared {
    fn new() -> Self {
        Self {
            tracker: Arc::new(Mutex::new(LastKnown::default())),
            guard: Arc::new(WriteGuard::new(GUARD_WINDOW)),
            regen_lock: Arc::new(tokio::sync::Mutex::new(())),
        }
    }
}

/// Last verified generated bytes per destination (back-propagation baseline).
#[derive(Debug, Default)]
struct LastKnown {
    entries: HashMap<PathBuf, Vec<u8>>,
}

/// Watcher-loop outcome: reload the cycle or quit entirely.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum SpinOutcome {
    Reload,
    Quit,
}

/// One watch cycle: loaded context plus subscriptions for this generation.
struct Cycle {
    context: Arc<ProjectContext>,
    subscriptions: Arc<Subscriptions>,
    shared: Shared,
}

impl Cycle {
    /// Load, capture pending hand-edits, write the full plan (template wins),
    /// reapply captured edits, and subscribe to this generation's inputs.
    async fn start(options: &Options, shared: &Shared) -> crate::Result<Self> {
        let context = Arc::new(generate::load_context(options).await?);
        let groups = generate::group_members(&context)?;
        let pending = capture_pending(&groups, &shared.tracker);

        let plan = generate::render_plan(&context, &groups)?;
        // Full-start prune only: diff the plan against the manifest and
        // remove clean orphans. Incremental regenerations below never prune.
        generate::prune_orphans(&context, &plan);
        generate::write_plan(&plan)?;
        generate::save_manifest_for_plan(&context, &plan);
        {
            let mut tracker = lock_tracker(&shared.tracker);
            tracker.entries.retain(|dest, _| groups.contains_key(dest));
            for write in &plan {
                shared.guard.note_write(&write.dest);
                tracker
                    .entries
                    .insert(write.dest.clone(), write.content.clone());
            }
        }
        tracing::info!(files = plan.len(), "generated configuration files");

        for (dest, last, captured) in &pending {
            let forward = plan
                .iter()
                .find(|write| write.dest == *dest)
                .map(|write| write.content.clone())
                .unwrap_or_default();
            reapply_pending(&context, &groups, dest, last, captured, &forward, shared);
        }

        let subscriptions = Arc::new(Subscriptions::build(&context, &groups)?);
        Ok(Self {
            context,
            subscriptions,
            shared: Shared {
                tracker: Arc::clone(&shared.tracker),
                guard: Arc::clone(&shared.guard),
                regen_lock: Arc::clone(&shared.regen_lock),
            },
        })
    }

    /// Run the watcher until a config change (reload) or interrupt (quit).
    async fn spin(&self) -> crate::Result<SpinOutcome> {
        let reload = Arc::new(AtomicBool::new(false));
        let wx = Watchexec::new({
            let context = Arc::clone(&self.context);
            let subscriptions = Arc::clone(&self.subscriptions);
            let shared = self.shared.clone();
            let reload = Arc::clone(&reload);
            let runtime = tokio::runtime::Handle::current();

            move |mut action| {
                if action.signals().any(|signal| signal == Signal::Interrupt) {
                    action.quit();
                    return action;
                }
                let paths: HashSet<PathBuf> =
                    action.paths().map(|(path, _)| path.to_owned()).collect();
                match classify(&paths, &subscriptions, &shared.guard) {
                    Dispatch::Reload => {
                        tracing::info!("configuration change detected, re-evaluating");
                        reload.store(true, Ordering::Relaxed);
                        action.quit();
                    }
                    Dispatch::Regenerate { forward, backprop } => {
                        if forward.is_empty() && backprop.is_empty() {
                            return action;
                        }
                        let context = Arc::clone(&context);
                        let subscriptions = Arc::clone(&subscriptions);
                        let shared = shared.clone();
                        runtime.spawn(async move {
                            let _locked = shared.regen_lock.lock().await;
                            if !forward.is_empty()
                                && let Err(err) =
                                    regenerate(&context, &subscriptions, &forward, &shared)
                            {
                                tracing::error!(
                                    "regeneration failed: {err:?} (watching continues)"
                                );
                            }
                            for dest in &backprop {
                                if let Err(err) =
                                    handle_backprop(&context, &subscriptions, dest, &shared)
                                {
                                    tracing::error!(
                                        "back propagation failed: {err:?} (watching continues)"
                                    );
                                }
                            }
                        });
                    }
                    Dispatch::Ignore => {}
                }
                action
            }
        })
        .map_err(|err| {
            crate::invalid(
                Path::new("watch"),
                format!("cannot start file watcher: {err}"),
            )
        })?;

        wx.config.pathset(self.subscriptions.watch_paths());
        wx.main()
            .await
            .map_err(|err| {
                crate::invalid(Path::new("watch"), format!("file watcher failed: {err}"))
            })?
            .map_err(|err| {
                crate::invalid(Path::new("watch"), format!("file watcher failed: {err}"))
            })?;

        Ok(if reload.load(Ordering::Relaxed) {
            SpinOutcome::Reload
        } else {
            SpinOutcome::Quit
        })
    }
}

fn lock_tracker(tracker: &Arc<Mutex<LastKnown>>) -> std::sync::MutexGuard<'_, LastKnown> {
    tracker.lock().unwrap_or_else(|poisoned| {
        tracing::warn!("tracker lock poisoned, recovering");
        poisoned.into_inner()
    })
}

/// Regenerate destination groups from current disk state.
fn regenerate(
    context: &ProjectContext,
    subscriptions: &Subscriptions,
    dests: &[PathBuf],
    shared: &Shared,
) -> crate::Result<()> {
    for dest in dests {
        let Some(members) = subscriptions.groups.get(dest) else {
            continue;
        };
        let group = generate::render_group(dest, members, context)?;
        let content = generate::preserve_group(dest, &group.content, members)?;
        generate::write_plan(&[crate::generate::PlannedWrite {
            dest: dest.clone(),
            content: content.clone(),
            mode: group.mode,
        }])?;
        generate::record_manifest_entry(context, dest, &content);
        shared.guard.note_write(dest);
        lock_tracker(&shared.tracker)
            .entries
            .insert(dest.to_path_buf(), content);
        tracing::info!(dest = %dest.display(), "regenerated after file change");
    }
    Ok(())
}

/// Capture hand-edits to known back-propagated destinations before the
/// forward write wins. First-cycle destinations initialize, never capture.
fn capture_pending(
    groups: &BTreeMap<PathBuf, Vec<GroupMember>>,
    tracker: &Arc<Mutex<LastKnown>>,
) -> Vec<(PathBuf, Vec<u8>, Vec<u8>)> {
    let tracked = lock_tracker(tracker);
    let mut pending = Vec::new();
    for (dest, members) in groups {
        if !members
            .iter()
            .any(|member| member.template.back_propagate == Some(true))
        {
            continue;
        }
        let Some(last) = tracked.entries.get(dest) else {
            continue;
        };
        match std::fs::read(dest) {
            Ok(current) if current != *last => {
                pending.push((dest.clone(), last.clone(), current));
            }
            _ => {}
        }
    }
    pending
}

/// Reapply one captured hand-edit onto fresh template output.
///
/// Template wins first (already written); the captured diff folds into the
/// override with a safety replay against the desired output. Failures log
/// loudly with a recovery snapshot and keep the template output.
#[allow(clippy::too_many_arguments)]
fn reapply_pending(
    context: &ProjectContext,
    groups: &BTreeMap<PathBuf, Vec<GroupMember>>,
    dest: &Path,
    last: &[u8],
    captured: &[u8],
    forward: &[u8],
    shared: &Shared,
) {
    let Some(members) = groups.get(dest) else {
        return;
    };
    let files = match read_member_files(context, members) {
        Ok(files) => files,
        Err(err) => {
            tracing::error!("back propagation failed: {err:?} (watching continues)");
            return;
        }
    };
    let views = match snapshot_members(members, &files) {
        Ok(views) => views,
        Err(err) => {
            tracing::error!("back propagation failed: {err:?} (watching continues)");
            return;
        }
    };
    match backprop::reapply(dest, last, captured, forward, &views) {
        Ok(BackpropOutcome::Applied {
            member,
            new_override_text,
            replay_bytes,
        }) => {
            if let Err(err) = apply_backprop(
                context,
                members,
                &member,
                new_override_text,
                dest,
                &replay_bytes,
                shared,
            ) {
                tracing::error!("back propagation failed: {err:?} (watching continues)");
            } else {
                tracing::info!(
                    dest = %dest.display(),
                    template = %member,
                    "reapplied hand-edit after template update"
                );
            }
        }
        Ok(BackpropOutcome::NoChange) => {}
        Err(err) => {
            tracing::error!("back propagation failed: {err:?} (watching continues)");
        }
    }
}

/// Owned template, override, and local override text for one member.
struct MemberFiles {
    template_text: String,
    override_text: Option<String>,
    local_text: Option<String>,
    override_path: PathBuf,
    local_path: Option<PathBuf>,
}

/// Read fresh file contents for every group member.
///
/// Whitespace-only files count as missing, matching generation.
fn read_member_files(
    context: &ProjectContext,
    members: &[GroupMember],
) -> crate::Result<Vec<MemberFiles>> {
    members
        .iter()
        .map(|member| {
            let template_path = member.source_root.join(member.template.template_path()?);
            let template_text = crate::read_file(&template_path)?;
            let override_path = override_path_for(context, member)?;
            let override_text = read_layer(&override_path, "override file")?;
            let (local_path, local_text) = match member
                .template
                .local_override_file
                .as_deref()
                .filter(|name| !name.trim().is_empty())
            {
                Some(name) => {
                    let local_path = override_path
                        .parent()
                        .unwrap_or_else(|| Path::new("."))
                        .join(name);
                    let local_text = read_layer(&local_path, "local override file")?;
                    (Some(local_path), local_text)
                }
                None => (None, None),
            };
            Ok(MemberFiles {
                template_text,
                override_text,
                local_text,
                override_path,
                local_path,
            })
        })
        .collect()
}

/// Read one optional layer file.
fn read_layer(path: &Path, what: &str) -> crate::Result<Option<String>> {
    match std::fs::read(path) {
        Ok(bytes) if bytes.iter().all(u8::is_ascii_whitespace) => Ok(None),
        Ok(bytes) => Ok(Some(String::from_utf8(bytes.to_vec()).map_err(|err| {
            crate::invalid(path, format!("file is not valid UTF-8: {err}"))
        })?)),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(err) => Err(crate::invalid(path, format!("cannot read {what}: {err}"))),
    }
}

/// Build borrowed back-propagation views over owned file snapshots.
fn snapshot_members<'a>(
    members: &'a [GroupMember],
    files: &'a [MemberFiles],
) -> crate::Result<Vec<MemberView<'a>>> {
    members
        .iter()
        .zip(files.iter())
        .map(|(member, file)| {
            let generated_filename = member.template.resolved_generated_file()?;
            Ok(MemberView {
                name: member.name.as_str(),
                labels: &member.labels,
                override_path: Some(file.override_path.as_path()),
                local_path: file.local_path.as_deref(),
                template_text: file.template_text.as_str(),
                override_text: file.override_text.as_deref(),
                local_text: file.local_text.as_deref(),
                strategy: crate::merge::effective_strategy(&member.template, &generated_filename)?,
                policy: member.template.array_policy.unwrap_or_default(),
                back_propagate: member.template.back_propagate.unwrap_or(false),
                ignore_keys: parse_ignore_patterns(&member.template.backprop_ignore)?,
                ignore_values: parse_ignore_patterns(&member.template.backprop_ignore_values)?,
            })
        })
        .collect()
}

/// Parse ignore patterns (validated upstream; failures stay loud).
fn parse_ignore_patterns(
    patterns: &[String],
) -> crate::Result<Vec<crate::backprop::IgnorePattern>> {
    patterns
        .iter()
        .map(|pattern| {
            crate::backprop::IgnorePattern::parse(pattern).map_err(|reason| {
                crate::invalid(
                    Path::new("templatry.source.toml"),
                    format!("invalid ignore pattern `{pattern}`: {reason}"),
                )
            })
        })
        .collect()
}

/// Handle a generated-file change on a back-propagated destination.
fn handle_backprop(
    context: &ProjectContext,
    subscriptions: &Subscriptions,
    dest: &Path,
    shared: &Shared,
) -> crate::Result<()> {
    let Some(members) = subscriptions.groups.get(dest) else {
        return Ok(());
    };
    let current = match std::fs::read(dest) {
        Ok(bytes) => bytes,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => {
            tracing::info!(dest = %dest.display(), "generated file deleted, restoring");
            return regenerate(context, subscriptions, &[dest.to_path_buf()], shared);
        }
        Err(err) => {
            return Err(crate::invalid(
                dest,
                format!("cannot read generated file: {err}"),
            ));
        }
    };
    let last = lock_tracker(&shared.tracker).entries.get(dest).cloned();
    let Some(last) = last else {
        return regenerate(context, subscriptions, &[dest.to_path_buf()], shared);
    };
    let files = read_member_files(context, members)?;
    let views = snapshot_members(members, &files)?;
    match backprop::backpropagate(dest, &last, &current, &views)? {
        BackpropOutcome::Applied {
            member,
            new_override_text,
            replay_bytes,
        } => {
            apply_backprop(
                context,
                members,
                &member,
                new_override_text,
                dest,
                &replay_bytes,
                shared,
            )?;
            tracing::info!(
                dest = %dest.display(),
                template = %member,
                "back-propagated hand-edit into override"
            );
        }
        BackpropOutcome::NoChange => {}
    }
    Ok(())
}

/// Write a back-propagation result: override (unless unchanged) plus
/// regenerated destination.
fn apply_backprop(
    context: &ProjectContext,
    members: &[GroupMember],
    member: &str,
    new_override_text: Option<String>,
    dest: &Path,
    replay_bytes: &[u8],
    shared: &Shared,
) -> crate::Result<()> {
    let Some(winner) = members.iter().find(|candidate| candidate.name == member) else {
        return Err(crate::invalid(
            dest,
            format!("internal error: back-propagation winner `{member}` left its group"),
        ));
    };
    if let Some(text) = new_override_text {
        let override_path = override_path_for(context, winner)?;
        generate::atomic_write(override_path.as_path(), text.as_bytes(), None)?;
        shared.guard.note_write(&override_path);
    }
    generate::atomic_write(dest, replay_bytes, None)?;
    generate::record_manifest_entry(context, dest, replay_bytes);
    shared.guard.note_write(dest);
    lock_tracker(&shared.tracker)
        .entries
        .insert(dest.to_path_buf(), replay_bytes.to_vec());
    Ok(())
}

/// Absolute override path for one group member (overrides live in the
/// project, so the root is shared; the directory comes from the member's own
/// source defaults).
fn override_path_for(context: &ProjectContext, member: &GroupMember) -> crate::Result<PathBuf> {
    let template = &member.template;
    Ok(absolute(
        &context
            .project_root
            .join(template.resolved_override_dir(&member.configs))
            .join(template.resolved_override_file().map_err(|err| {
                crate::invalid(
                    &context.project_file,
                    format!("cannot resolve override path: {err}"),
                )
            })?),
    ))
}

// ---- Subscriptions ----------------------------------------------------------

/// Watch subscriptions for one cycle: path maps plus watched directories.
struct Subscriptions {
    /// Override file → destination files it feeds.
    overrides: HashMap<PathBuf, Vec<PathBuf>>,
    /// Watched generated file → its destination (back-propagate members only).
    generated: HashMap<PathBuf, PathBuf>,
    /// Destination → group members for targeted regeneration.
    groups: HashMap<PathBuf, Vec<GroupMember>>,
    /// Project config file: change triggers a full reload.
    project_file: PathBuf,
    /// Source files for local sources: change triggers a full reload.
    source_files: Vec<PathBuf>,
    /// Parent directories watched non-recursively.
    watch_dirs: Vec<PathBuf>,
}

impl Subscriptions {
    /// Build subscriptions from a loaded context and its destination groups.
    fn build(
        context: &ProjectContext,
        groups: &BTreeMap<PathBuf, Vec<GroupMember>>,
    ) -> crate::Result<Self> {
        let mut overrides: HashMap<PathBuf, Vec<PathBuf>> = HashMap::new();
        let mut generated: HashMap<PathBuf, PathBuf> = HashMap::new();
        let mut groups_map: HashMap<PathBuf, Vec<GroupMember>> = HashMap::new();
        let mut watch_dirs: HashSet<PathBuf> = HashSet::new();

        for (dest, members) in groups {
            let dest_abs = absolute(dest);
            groups_map.insert(dest_abs.clone(), members.clone());
            if let Some(parent) = dest_abs.parent() {
                std::fs::create_dir_all(parent).map_err(|err| {
                    crate::invalid(
                        &dest_abs,
                        format!("cannot create generated directory: {err}"),
                    )
                })?;
                watch_dirs.insert(parent.to_path_buf());
            }
            let mut watches_generated = false;
            for member in members {
                let override_path = override_path_for(context, member)?;
                overrides
                    .entry(override_path.clone())
                    .or_default()
                    .push(dest_abs.clone());
                if let Some(name) = member
                    .template
                    .local_override_file
                    .as_deref()
                    .filter(|name| !name.trim().is_empty())
                {
                    // Local layers feed their destination like overrides do.
                    let local_path = absolute(
                        &override_path
                            .parent()
                            .unwrap_or_else(|| Path::new("."))
                            .join(name),
                    );
                    overrides
                        .entry(local_path)
                        .or_default()
                        .push(dest_abs.clone());
                }
                if member.template.back_propagate == Some(true) {
                    watches_generated = true;
                }
            }
            if watches_generated {
                generated.insert(dest_abs.clone(), dest_abs.clone());
            }
        }

        for dir in override_dirs(context)? {
            std::fs::create_dir_all(&dir).map_err(|err| {
                crate::invalid(&dir, format!("cannot create override directory: {err}"))
            })?;
            watch_dirs.insert(dir);
        }

        let project_file = absolute(&context.project_file);
        if let Some(parent) = project_file.parent() {
            watch_dirs.insert(parent.to_path_buf());
        }
        let mut source_files = Vec::new();
        for entry in &context.entries {
            if entry.kind == SourceKind::LocalDir {
                let source = absolute(&entry.root_dir.join(SOURCE_CONFIG_FILENAME));
                if let Some(parent) = source.parent() {
                    watch_dirs.insert(parent.to_path_buf());
                }
                source_files.push(source);
            }
        }

        Ok(Self {
            overrides,
            generated,
            groups: groups_map,
            project_file,
            source_files,
            watch_dirs: watch_dirs.into_iter().collect(),
        })
    }

    /// Watchexec pathset: every watched directory, non-recursive.
    fn watch_paths(&self) -> Vec<watchexec::WatchedPath> {
        self.watch_dirs
            .iter()
            .map(watchexec::WatchedPath::non_recursive)
            .collect()
    }
}

/// Override directories in use by enabled templates (absolute).
fn override_dirs(context: &ProjectContext) -> crate::Result<Vec<PathBuf>> {
    let mut dirs = HashSet::new();
    for entry in &context.entries {
        for name in &entry.enabled {
            let template = &entry.resolved[name];
            dirs.insert(absolute(
                &context
                    .project_root
                    .join(template.resolved_override_dir(&entry.source.configs)),
            ));
        }
    }
    Ok(dirs.into_iter().collect())
}

/// Absolute path, falling back to the raw path when the system call fails.
fn absolute(path: &Path) -> PathBuf {
    std::path::absolute(path).unwrap_or_else(|_| path.to_path_buf())
}

/// Same-file comparison robust to symlinks (macOS temp dirs) and deletions.
///
/// Both sides canonicalized when possible; otherwise (e.g. deletion events
/// for files that no longer exist) canonicalized parents plus file names are
/// compared, so symlinked prefixes still match.
fn same_file(left: &Path, right: &Path) -> bool {
    if let (Ok(left), Ok(right)) = (left.canonicalize(), right.canonicalize()) {
        return left == right;
    }
    match (parent_canonical(left), parent_canonical(right)) {
        (Some((left_dir, left_name)), Some((right_dir, right_name))) => {
            left_dir == right_dir && left_name == right_name
        }
        _ => absolute(left) == absolute(right),
    }
}

/// Canonicalized parent plus raw file name, if the parent resolves.
fn parent_canonical(path: &Path) -> Option<(PathBuf, std::ffi::OsString)> {
    Some((
        path.parent()?.canonicalize().ok()?,
        path.file_name()?.to_os_string(),
    ))
}

// ---- Dispatch ---------------------------------------------------------------

/// Watch-event dispatch decision.
#[derive(Debug, Clone, PartialEq, Eq)]
enum Dispatch {
    /// A config file changed: full reload plus resubscribe.
    Reload,
    /// Override changes regenerate forward; generated-file changes fold back.
    /// A destination in both comes from its override: forward wins.
    Regenerate {
        forward: Vec<PathBuf>,
        backprop: Vec<PathBuf>,
    },
    /// Nothing actionable (self-writes, unwatched paths).
    Ignore,
}

/// Classify changed paths against subscriptions (pure: unit-testable).
fn classify(
    paths: &HashSet<PathBuf>,
    subscriptions: &Subscriptions,
    guard: &WriteGuard,
) -> Dispatch {
    for path in paths {
        if same_file(path, &subscriptions.project_file)
            || subscriptions
                .source_files
                .iter()
                .any(|source| same_file(path, source))
        {
            return Dispatch::Reload;
        }
    }
    let mut forward: Vec<PathBuf> = Vec::new();
    let mut backprop: Vec<PathBuf> = Vec::new();
    for path in paths {
        if guard.is_self_write(path) {
            continue;
        }
        for (override_path, override_dests) in &subscriptions.overrides {
            if same_file(path, override_path) {
                forward.extend(override_dests.iter().cloned());
            }
        }
        if let Some((_, dest)) = subscriptions
            .generated
            .iter()
            .find(|(generated, _)| same_file(path, generated))
        {
            backprop.push(dest.clone());
        }
    }
    forward.sort();
    forward.dedup();
    backprop.retain(|dest| !forward.contains(dest));
    backprop.sort();
    backprop.dedup();
    if forward.is_empty() && backprop.is_empty() {
        Dispatch::Ignore
    } else {
        Dispatch::Regenerate { forward, backprop }
    }
}

// ---- Self-trigger guard -----------------------------------------------------

/// Remembers our own writes; events inside the window are our echo.
struct WriteGuard {
    writes: Mutex<HashMap<PathBuf, Instant>>,
    window: Duration,
}

impl WriteGuard {
    fn new(window: Duration) -> Self {
        Self {
            writes: Mutex::new(HashMap::new()),
            window,
        }
    }

    /// Record a write we performed.
    fn note_write(&self, path: &Path) {
        if let Ok(mut writes) = self.writes.lock() {
            writes.insert(absolute(path), Instant::now());
        }
    }

    /// True when we wrote this path inside the guard window.
    fn is_self_write(&self, path: &Path) -> bool {
        let Ok(mut writes) = self.writes.lock() else {
            return false;
        };
        let now = Instant::now();
        writes.retain(|_, written| now.duration_since(*written) <= self.window);
        let key = absolute(path);
        writes.keys().any(|written| same_file(&key, written))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_subscriptions(dir: &Path) -> Subscriptions {
        let override_path = dir.join("override.json");
        let dest = dir.join("generated").join("out.json");
        let generated = dir.join("generated").join("live.json");
        Subscriptions {
            overrides: [(override_path, vec![dest.clone()])].into_iter().collect(),
            generated: [(generated.clone(), generated)].into_iter().collect(),
            groups: HashMap::new(),
            project_file: dir.join(".config").join("templatry.toml"),
            source_files: vec![dir.join("templates").join("templatry.source.toml")],
            watch_dirs: Vec::new(),
        }
    }

    fn set(paths: &[PathBuf]) -> HashSet<PathBuf> {
        paths.iter().cloned().collect()
    }

    /// Fresh tempdir-backed subscriptions plus write guard for dispatch
    /// tests. The tempdir is returned to keep it alive.
    fn dispatch_fixture() -> (tempfile::TempDir, PathBuf, Subscriptions, WriteGuard) {
        let dir = tempfile::tempdir().expect("tempdir");
        let root = dir.path().canonicalize().expect("canonicalize");
        let subscriptions = test_subscriptions(&root);
        let guard = WriteGuard::new(GUARD_WINDOW);
        (dir, root, subscriptions, guard)
    }

    #[test]
    fn dispatch_override_regenerates_forward() {
        let (_dir, root, subscriptions, guard) = dispatch_fixture();

        let paths = set(&[root.join("override.json")]);
        let Dispatch::Regenerate { forward, backprop } = classify(&paths, &subscriptions, &guard)
        else {
            panic!("expected regeneration");
        };
        assert_eq!(forward, [root.join("generated").join("out.json")]);
        assert!(backprop.is_empty());
    }

    #[test]
    fn dispatch_generated_folds_back() {
        let (_dir, root, subscriptions, guard) = dispatch_fixture();

        let paths = set(&[root.join("generated").join("live.json")]);
        let Dispatch::Regenerate { forward, backprop } = classify(&paths, &subscriptions, &guard)
        else {
            panic!("expected regeneration");
        };
        assert!(forward.is_empty());
        assert_eq!(backprop, [root.join("generated").join("live.json")]);
    }

    #[test]
    fn dispatch_config_changes_reload() {
        let (_dir, root, subscriptions, guard) = dispatch_fixture();

        let project = set(&[root.join(".config").join("templatry.toml")]);
        assert_eq!(classify(&project, &subscriptions, &guard), Dispatch::Reload);

        let source = set(&[root.join("templates").join("templatry.source.toml")]);
        assert_eq!(classify(&source, &subscriptions, &guard), Dispatch::Reload);
    }

    #[test]
    fn dispatch_ignores_unknown_and_self_writes() {
        let (_dir, root, subscriptions, guard) = dispatch_fixture();

        let unknown = set(&[root.join("unrelated.txt")]);
        assert_eq!(classify(&unknown, &subscriptions, &guard), Dispatch::Ignore);

        guard.note_write(&root.join("generated").join("live.json"));
        let echo = set(&[root.join("generated").join("live.json")]);
        assert_eq!(classify(&echo, &subscriptions, &guard), Dispatch::Ignore);

        // A mixed event still regenerates for the real change.
        let mixed = set(&[root.join("unrelated.txt"), root.join("override.json")]);
        assert!(matches!(
            classify(&mixed, &subscriptions, &guard),
            Dispatch::Regenerate { .. }
        ));
    }

    #[test]
    fn guard_window_zero_never_matches() {
        let guard = WriteGuard::new(Duration::ZERO);
        let path = Path::new("/tmp/some-output.json");
        guard.note_write(path);
        assert!(!guard.is_self_write(path));
        assert!(!guard.is_self_write(Path::new("/tmp/other.json")));
    }

    #[test]
    fn same_file_survives_symlinks() {
        let dir = tempfile::tempdir().expect("tempdir");
        let raw = dir.path().join("file.json");
        std::fs::write(&raw, "{}").expect("write");
        let canonical = raw.canonicalize().expect("canonicalize");
        assert!(same_file(&raw, &canonical));
        assert!(!same_file(&raw, &dir.path().join("other.json")));
    }

    fn backprop_context(
        dir: &Path,
        template_text: &str,
        override_text: Option<&str>,
    ) -> (ProjectContext, BTreeMap<PathBuf, Vec<GroupMember>>) {
        use crate::config::{Configs, SourceFile, Template};

        let templates = dir.join("templates");
        std::fs::create_dir_all(&templates).expect("mkdirs");
        std::fs::write(templates.join("app.json"), template_text).expect("write template");
        std::fs::write(
            templates.join("templatry.source.toml"),
            "[templates.app]\ntemplate = \"app.json\"\nback_propagate = true\n",
        )
        .expect("write source");
        if let Some(text) = override_text {
            let overrides = dir.join(".config");
            std::fs::create_dir_all(&overrides).expect("mkdirs");
            std::fs::write(overrides.join("app.json"), text).expect("write override");
        }
        let mut templates_map = BTreeMap::new();
        templates_map.insert(
            "app".to_string(),
            Template {
                template: Some("app.json".to_string()),
                extends: None,
                override_file: None,
                override_dir: None,
                local_override_file: None,
                generated_file: None,
                generated_dir: None,
                strategy: None,
                array_policy: Some(crate::config::ArrayPolicy::Union),
                back_propagate: Some(true),
                labels: Default::default(),
                backprop_ignore: Vec::new(),
                backprop_ignore_values: Vec::new(),
            },
        );
        let context = ProjectContext {
            project_file: dir.join(".config").join("templatry.toml"),
            project_root: dir.to_path_buf(),
            entries: vec![crate::generate::ContextEntry {
                name: String::new(),
                root_dir: templates.clone(),
                source: SourceFile {
                    configs: Configs::default(),
                    abstracts: Default::default(),
                    templates: templates_map.clone(),
                    default: None,
                },
                resolved: templates_map,
                enabled: ["app".to_string()].into_iter().collect(),
                kind: SourceKind::LocalDir,
            }],
        };
        let groups = generate::group_members(&context).expect("groups");
        (context, groups)
    }

    #[test]
    fn capture_pending_collects_only_known_backprop_edits() {
        let dir = tempfile::tempdir().expect("tempdir");
        let (_context, groups) = backprop_context(dir.path(), "{\"k\": 1}", None);
        let dest = groups.keys().next().expect("one dest").clone();

        let tracker = Arc::new(Mutex::new(LastKnown::default()));
        // Unknown destination: initializes, never captures.
        assert!(capture_pending(&groups, &tracker).is_empty());

        let last = b"{\"k\": 1}\n".to_vec();
        std::fs::create_dir_all(dest.parent().expect("parent")).expect("mkdirs");
        std::fs::write(&dest, &last).expect("write dest");
        lock_tracker(&tracker)
            .entries
            .insert(dest.clone(), last.clone());
        assert!(capture_pending(&groups, &tracker).is_empty());

        let captured = b"{\"k\": 2}\n".to_vec();
        std::fs::write(&dest, &captured).expect("hand-edit");
        let pending = capture_pending(&groups, &tracker);
        assert_eq!(pending, [(dest, last, captured)]);
    }

    #[test]
    fn reapply_pending_reproduces_hand_edit_after_bump() {
        let dir = tempfile::tempdir().expect("tempdir");
        let (context, groups) = backprop_context(dir.path(), "{\"k\": 1, \"u\": \"old\"}", None);
        let dest = groups.keys().next().expect("one dest").clone();

        let last = b"{\n  \"k\": 1,\n  \"u\": \"old\"\n}\n".to_vec();
        let captured = b"{\n  \"k\": 2,\n  \"u\": \"old\"\n}\n".to_vec();
        // Template bumped underneath the pending edit.
        std::fs::write(
            context.entries[0].root_dir.join("app.json"),
            "{\"k\": 1, \"u\": \"new\", \"n\": true}",
        )
        .expect("bump template");
        let forward = b"{\n  \"k\": 1,\n  \"n\": true,\n  \"u\": \"new\"\n}\n".to_vec();

        let shared = Shared::new();
        reapply_pending(
            &context, &groups, &dest, &last, &captured, &forward, &shared,
        );

        let override_path = dir.path().join(".config").join("app.json");
        assert_eq!(
            std::fs::read_to_string(&override_path).expect("read override"),
            "{\n  \"k\": 2\n}\n"
        );
        assert_eq!(
            std::fs::read(&dest).expect("read dest"),
            b"{\n  \"k\": 2,\n  \"n\": true,\n  \"u\": \"new\"\n}\n"
        );
        assert_eq!(
            lock_tracker(&shared.tracker).entries.get(&dest),
            Some(&b"{\n  \"k\": 2,\n  \"n\": true,\n  \"u\": \"new\"\n}\n".to_vec())
        );
    }
}
